spring:
  application:
    name: gateway
  cloud:
    # 网关
    gateway:
      routes:
        - id: gateway-oauth2
          uri: http://localhost:9009/oauth2
          predicates:
            - Path=/oauth2/**

        - id: gateway-system
          uri: http://localhost:9002/system
          predicates:
            - Path=/system/**

        - id: gateway-sms
          uri: http://localhost:9003/sms
          predicates:
            - Path=/sms/**

        - id: gateway-mq
          uri: http://localhost:9004/mq
          predicates:
            - Path=/mq/**
      globalcors:
        # 跨域配置
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH

server:
  port: 9000

logging:
  level:
    org.springframework.cloud.gateway.handler: debug

# 自定义属性
# 地址白名单
custom:
  gateway:
    allowed-urls: /oauth2/login,/oauth2/refreshToken,/oauth2/getValidateCode

