server:
  port: 9003
  servlet:
    context-path: /sms

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: qmplatform
    password: qmplatform
    publisher-confirms: true
    publisher-returns: true
  mail:
    host: smtp.163.com
    port: 25
    username: qmplatform@163.com
    password: ENC(enc_wd)
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            #开启SSL安全连接(有的邮箱不需要,QQ邮箱需要,不需要时改为false)
            enable: true
            required: true
  application:
    name: sms

jasypt:
  encryptor:
    password: qcz
