server:
  port: 9002
  servlet:
    context-path: /system
spring:
  application:
    name: system-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/qmplatform
    username: postgres
    password: ENC(enc_wd)
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
# 加密秘钥
jasypt:
  encryptor:
    password: qcz

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/*Mapper.xml

# pagehelper 分页插件
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.qcz.qmplatform.system.mapper: debug
